### ISSUE TITLE
Push module to NPM

### ISSUE THREAD

**Issue by munro** [augustohp/Priority-Queue-NodeJS#3]
v0.0.1 is still registered with NPM

https://npmjs.org/package/priority-queue

**Comment by munro** [comment]
Also, please remove these lines so I can install it in the latest version of Node.

https://github.com/augustohp/Priority-Queue-NodeJS/blob/master/package.json#L15-L17

Finally, please consider setting the project up with Travis-ci.  It will allow people to quickly know if your project works for their version of Node!  It does work for v0.11.x.

http://about.travis-ci.org/docs/user/languages/javascript-with-nodejs/

**Comment by augustohp** [comment]
https://www.npmjs.org/package/queue-priority
