### ISSUE TITLE
r u kidding?

### ISSUE THREAD

**Issue by hellocodeM** [augustohp/Priority-Queue-NodeJS#4]
It maybe too slow.

**Comment by augustohp** [comment]
> It maybe too slow.

It certainly is, the algorithm being pretty simple should stand to the point "I didn't care for performance".

I used this many years ago, with Node 0.2 for a quick and simple bid engine to sort 3 to 10 items; as my main issues were with concurrency to the persistence layer I really didn't put much effort on anything else.

I am sorry if this offended you in any way by not being a joke, this was never the intention.
